### ISSUE TITLE
Error when querying the server

### ISSUE THREAD

**Issue by martinmolin** [skytable/client-rust#1]
**Problem:**
Bad response when querying:
```
C:\Users\cmm\dev\local\skytest> cargo run  
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target\debug\skytest.exe`
Response: Item(Str("HEY!"))
Response: Item(Str("HEY!"))
Response: InvalidResponse
Response: InvalidResponse
Response: InvalidResponse
Response: Item(Str("HEY!"))
Response: InvalidResponse
Response: Item(RespCode(PacketError))
Response: InvalidResponse
Response: InvalidResponse
Response: Item(RespCode(PacketError))
```

**Platform:**
Windows 10 Pro 20H2
skyd 0.5.2 and 0.5.1

**I tried this:**
Cargo.toml
```
[package]
name = "skytest"
version = "0.1.0"
edition = "2018"

[dependencies]
skytable = "0.2.3"
tokio = {version="1.5.0", features=["full"]}
```

main.rs
```
use skytable::{Connection, Query};

#[tokio::main]
async fn main() -> std::io::Result<()> {
    let mut con = Connection::new("127.0.0.1", 2003).await?;
    loop {
        let mut query = Query::new();
        query.arg("heya");
        let response = con.run_simple_query(query).await?;
        println!("Response: {:?}", response);
        std::thread::sleep(std::time::Duration::from_millis(200));
    }
}
```

**Comment by ohsayan** [comment]
Which driver version are you using?

**Comment by martinmolin** [comment]
skytable = "0.2.3" in the Cargo.toml :)

**Comment by ohsayan** [comment]
What happens if you increase the sleep duration?

**Comment by martinmolin** [comment]
It didn't seem to make a difference, I was initially doing 1 second but it was quicker to see the issue with 200ms! (Tried 5 seconds as well, it also got errors)

**Comment by ohsayan** [comment]
This is interesting. It doesn't look like it's a server error but likely something wrong with the client

**Comment by ohsayan** [comment]
Can you try doing this instead of your `println`:
```
println!("{:?}", con)
```

**Comment by martinmolin** [comment]
Connection doesn't seem to implement Debug! I just tried the same code on Ubuntu and it seems to work flawlessly.

**Comment by ohsayan** [comment]
I suspect it to be the `size_count` field not being reset

**Comment by martinmolin** [comment]
Server on Windows, Client on Windows = Errors
Server on Windows/Ubuntu, Client on Ubuntu = No Errors

**Comment by ohsayan** [comment]
Can you try changing the skytable dependency in your `Cargo.toml` to:
```toml
skytable = { git = "https://github.com/skytable/client-rust", branch = "next" }
```

PS: I just pushed some changes; let me know if that changes any thing

**Comment by martinmolin** [comment]
Just tried it, seems like it's the exact same behavior as before on Windows (There's still an issue with the responses)

**Comment by ohsayan** [comment]
Just implemented Debug, can you `cargo clean` and `cargo run` while debug printing `con`

**Comment by martinmolin** [comment]
```
C:\Users\cmm\dev\local\skytest> cargo run
   Compiling skytest v0.1.0 (C:\Users\cmm\dev\local\skytest)
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
     Running `target\debug\skytest.exe`
Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:64306, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
Item(Str("HEY!"))

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:64306, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
InvalidResponse

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:64306, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
InvalidResponse

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:64306, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
Item(RespCode(PacketError))

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:64306, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
Item(RespCode(PacketError))

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:64306, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
InvalidResponse

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:64306, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
Item(Str("HEY!"))

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:64306, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
Item(Str("HEY!"))

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:64306, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
InvalidResponse

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:64306, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
Item(Str("HEY!"))
```

**Comment by ohsayan** [comment]
Can't repro on macOS/Ubuntu

**Comment by ohsayan** [comment]
Can you do this: `watch -n0.2 'skysh -e heya'` (with the skytable shell this time)
(hoping windows has some ncurses)
This might help: https://unix.stackexchange.com/questions/38910/cygwin-has-no-watch-command/38912

**Comment by ohsayan** [comment]
@martinmolin Wait, ... could you print `con` before  your `let response ...`

Sorry for having you do all this; don't have a Windows installation around :(

**Comment by martinmolin** [comment]
Printing con before and after running the query:
```
Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65005, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
Item(Str("HEY!"))
Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65005, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65005, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
Item(Str("HEY!"))
Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65005, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65005, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
InvalidResponse
Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65005, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65005, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
Item(Str("HEY!"))
Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65005, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }

Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65005, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
InvalidResponse
Connection { stream: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65005, peer: 127.0.0.1:2003, socket: 364 }) }, buffer: b"" }
```

**Comment by martinmolin** [comment]
It's completely fine btw! Thank you for investigating the issue, let me try to see if I can do the skysh watch thing :)

**Comment by ohsayan** [comment]
How is this even happening? The buffer is perfectly empty! Does this only happen for `heya`? Could you try setting a key like: `set verylongkey 123456789123456789` and then running `get x` in your loop instead of `heya`?

**Comment by martinmolin** [comment]
Exactly the same behavior, I actually ran into the issue using a GET and a key but wanted to simplify it as much as possible for the report :)

**Comment by ohsayan** [comment]
@martinmolin, can you:

1. try changing your skytable dep branch to 'syncapi':
```
skytable = { git = "https://github.com/skytable/client-rust", branch = "syncapi" }
```
2. and then running your loop following an example like this: https://raw.githubusercontent.com/skytable/client-rust/syncapi/examples/sync-api/src/main.rs

**Comment by ohsayan** [comment]
Update, `sync` and `async` have just been feature gated on `syncapi`. 
- To test the `async` API change your dep to:
```toml
skytable = { git = "https://github.com/skytable/client-rust", branch = "syncapi", features=["async"] }
```
- To test the `sync` API change your dep to:
```toml
skytable = { git = "https://github.com/skytable/client-rust", branch = "syncapi", features=["sync"] }
```
